org: tigaron
service: TrainChecker

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}

functions:
  Station:
    handler: handler.station
    name: ${self:service}-Station-${sls:stage}
    description: Endpoint to check train schedule based on station
    memorySize: 1024
    timeout: 10
    events:
      - httpApi:
          path: /station
          method: get

plugins:
  - serverless-offline
